# Code Generated by Sidekick is for learning and experimentation purposes only.
from airflow import DAG
from airflow.providers.databricks.operators.databricks import DatabricksRunNowOperator
from datetime import datetime, timedelta

# Default arguments for the DAG
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# Define the DAG
with DAG(
    'databricks_job_trigger',
    default_args=default_args,
    description='A simple DAG to trigger Databricks job',
    schedule_interval=timedelta(days=1),
    start_date=datetime(2023, 1, 1),
    catchup=False,
) as dag:

    # Define the task to trigger the Databricks job
    run_databricks_job = DatabricksRunNowOperator(
        task_id='run_databricks_job_3',
        databricks_conn_id='dbr_ws',
        job_id=737065150116241,
    )

    run_databricks_job
