
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      curl -sSL install.astronomer.io | sudo bash
      cd $(Build.SourcesDirectory)
      files=$(git diff --name-only $(git rev-parse HEAD~1) -- .)
      dags_only=1
      echo "DEPLOYMENT ID $DEPLOYMENT_ID"
      for file in $files; do
        if [[ $file != "$DAG_FOLDER"* ]]; then
          echo "$file is not a dag, triggering a full image build"
          dags_only=0
          break
        fi
      done
      if [ $dags_only == 1 ]; then
        astro deploy --dags $DEPLOYMENT_ID
      fi
      if [ $dags_only == 0 ]; then
        astro deploy $DEPLOYMENT_ID
      fi
    displayName: 'Deploy to Astronomer'
